example/src/AppBundle/Resources/views/Default/login.html.twig

Replaces “scope: ‘openid profile’” with “scope: ‘openid name email’”.

Replaces scope: 'openid profile'

---

CHANGELOG.md
src/Resources/config/services.yml

[Upgrade](https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md#yaml) for the 3.0 branch of Symfony requires that backslashes must be escaped when inside double quotes.

YAML files that use double quotes need to escape backslashes

---

Tests/Security/JWTAuthenticatorTest.php
Tests/bootstrap.php
composer.json
phpunit.xml.dist
src/Security/JWTAuthenticator.php

Updated `JWTAuthenticator` to use Trait rather than extending ContainerAware.
Updated tests and bundle configuration.

Symfony 3.0 Changes

---

src/Resources/config/services.yml

Fix to avoid errors such as:
```
Not quoting the scalar "%jwt_auth.client_id%" starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0: 1x
1x in DefaultControllerTest::testIndex from Tests\AppBundle\Controller
Not quoting the scalar "%jwt_auth.client_secret%" starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0: 1x
1x in DefaultControllerTest::testIndex from Tests\AppBundle\Controller
Not quoting the scalar "%jwt_auth.domain%" starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0: 1x
1x in DefaultControllerTest::testIndex from Tests\AppBundle\Controller
```

Fix deprecation warnings SF 3.1

---

.travis.yml
Tests/Functional/BundleInitializationTest.php
Tests/Functional/config/cache.yml
Tests/Security/JWTAuthenticatorTest.php
composer.json
src/DependencyInjection/Configuration.php
src/DependencyInjection/JWTAuthExtension.php
src/Resources/config/services.yml
src/Security/Auth0Service.php

This will fix #50. 
I see that you are not running any test on travis. And you barely have any tests... I added some smoke tests. 
I also allowed Symfony 2.8 since it is the same as 3.0.

Added support for cache

---

composer.json

This allows for installation under symfony/symfony 4.x.

Allow symfony/framework-bundle 4.x

---

src/Security/Core/JWTUserProviderInterface.php

Made `Auth0\JWTAuthBundle\Security\Core\JWTUserProviderInterface` comply with PHP7 strict settings, since the type-hinting was either missing or wrong.
Following a test implementation of the Auth0 bundle in a PHP 7.2 / Symfony 4.2 stack (using your own examples), we found out that PHPStan was (accurately) complaining about missing/wrong type-hinting.
Ran `vendor/bin/phpunit` with following output:
```
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.
....                                                                4 / 4 (100%)
Time: 141 ms, Memory: 12.00MB
OK (4 tests, 12 assertions)
```
[x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRI …

Php7 strict fix

---

src/Security/Core/JWTInfoNotFoundException.php

Fixed deprecation notices for `Auth0\JWTAuthBundle\Security\Core\JWTInfoNotFoundException` exception by extending `__serialize` and `__unserialize` instead of `serialize` and `unserialize`.
Following an implementation on PHP 7.2 / Symfony 4.3, after writing tests for our implementation that are referencing the `JWTInfoNotFoundException` exception, and by using the PHPUnit Bridge from Symfony which checks for Symfony deprecations, it accurately outputted:
```
1x: The "Symfony\Component\Security\Core\Exception\AuthenticationException::serialize()" method is considered final since Symfony 4.3, use __serialize() instead. It may change without further notice as of its next major version. You should not extend it from "Auth0\JWTAuthBundle\Security\Core\JWTInfoNotFoundException".
1x in …
```

serialize/unserialize methods are deprecated since Symfony 4.3

---

.github/CODEOWNERS
src/DependencyInjection/Configuration.php

Fixed deprecated call with Symfony >= 4.3 
The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "jwt_auth" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.

Fixed deprecated root call

---

Tests/Security/Guard/JwtGuardAuthenticatorTest.php
Tests/Security/User/JwtUserProviderTest.php
src/Resources/config/services.yml
src/Security/Core/JWTUserProviderInterface.php
src/Security/Guard/JwtGuardAuthenticator.php
src/Security/User/JwtUserProvider.php

The current `SimplePreAuthenticator` implementation is deprecated since Symfony 4.2. The guard authentication system provides more flexibility to eg. more verbose responses concerning authentication. And it makes this bundle (better) forward-compatible with Symfony 5 and later.
This PR adds the following:
* A `JwtGuardAuthenticator` class with service definition to use in the `security.y(a)ml`.
* A `JwtUserProvider` which adheres to the `JWTUserProviderInterface`. It offers a basic user provider implementation by reading the information from the token and transforming it to a Symfony `User`.
* A docblock fix for `JWTUserProviderInterface::loadUserByJWT`.
At the moment the `JwtGuardAuthenticator` returns JSON responses, but I guess not everyone would want that.
If you'd like to provide …

GuardAuthenticator implementation for Symfony 2.8 and later

---

src/DependencyInjection/Configuration.php

Fix for the following:
`The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "jwt_auth" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.`
It's fixed in a BC way. From: https://github.com/symfony/monolog-bundle/pull/281/commits/45742f1a97291edd1401ecb58024488bbd793038

Fix deprecation Treebuilder::root

---

composer.json

This PR adds support for Symfony 5. I only changed the version in `composer.json`. 
Did some functional testing on my end, no additional entries in my log file and console. Seems to be working. 
I did not add test coverage, since I have no experience on that topic. I was able to run the tests, and got the following:
```
HPUnit 5.7.27 by Sebastian Bergmann and contributors.
......EEE..E...EE........                                         25 / 25 (100%)
Time: 691 ms, Memory: 12.00MB
There were 6 errors:
1) Auth0\JWTAuthBundle\Tests\Security\Guard\JwtGuardAuthenticatorTest::testGetUserReturnsUnknownUserWhenJwtDecodingFails
Function ReflectionType::__toString() is deprecated
/srv/api/vendor/auth0/jwt-auth-bundle/Tests/Security/Guard/JwtGuardAuthenticatorTest.php:105
2) …
```

Symfony 5 support

---

Tests/DependencyInjection/ConfigurationTest.php
src/DependencyInjection/Configuration.php

Fix **BC** introduced in last PR. Now the `authorized_issuer` can really be a string or an array. I also added tests to the `Configuration`
[x] This change adds test coverage
[x] All existing and new tests complete without errors

Configuration authorized_issuer string or array compatibility

---

.circleci/config.yml

This will fix codecov not being able to upload reports after rebasing a PR from the GH UI.

Fix codecov reporting invalid SHA1

---

src/Security/Guard/JwtGuardAuthenticator.php

Alternative to #96 (same rationale). This implementation is less intrusive.
Always populate the `token` property of the JWT object.
#96.
Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors. 
[x] This change adds test coverage
[x] All existing and new tests complete …

Give access to the raw JWT in the user provider (alternative implem)

---

Tests/Functional/BundleInitializationTest.php
src/Resources/config/services.yml

Allow to autowire the `Auth0Service` service.
Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors. 
[x] This change adds test coverage
[x] All existing and new tests complete without errors

Add support for autowiring

---

CHANGELOG.md
src/JWTAuthBundle.php

**Added**
- Add support for autowiring [\#94](https://github.com/auth0/jwt-auth-bundle/pull/94) ([dunglas](https://github.com/dunglas))
- Give access to the raw JWT in the user provider [\#97](https://github.com/auth0/jwt-auth-bundle/pull/97) ([dunglas](https://github.com/dunglas))
**Changed**
- Remove unused argument, and unused property [\#95](https://github.com/auth0/jwt-auth-bundle/pull/95) ([dunglas](https://github.com/dunglas))

Release 3.4.0 [SDK-1746]

---

README.md
Tests/Security/Helpers/JwtValidationsTest.php
src/DependencyInjection/JWTAuthExtension.php
src/Security/Helpers/JwtValidations.php

This PR adds support for validating an `org_id` claim on a JWT, necessary for Organizations (currently in a closed beta) support.
A new configuration variable is available:
```yaml
jwt_auth:
validations:
org_id: "%env(AUTH0_ORGANIZATION)%"
```
This will ensure the the `org_id` claim on a provided token matches the supplied value.
- PR adds `Auth0\JWTAuthBundle\Security\Helpers\JwtValidations::validateClaimAzp()` for processing this validation
- PR updates `Auth0\JWTAuthBundle\Security\Helpers\JwtValidations::validateClaims()` to trigger the validation during `Auth0\JWTAuthBundle\Security\Auth0Service::decodeJWT()` calls
- Adds tests around the new validation

[SDK-2377] Add optional validator for `org_id` on tokens, for Organizations support

---

src/Security/Guard/JwtGuardAuthenticator.php

It was brought to my attention that a change in the previous commit around PHP 8 support and PHP SDK updates would result in this bundle conflicting with other Guard bundles. This PR restores the behavior of the Authentication Bearer header check so that our bundle can co-exist with other Guard bundles.

Fix JwtGuardAuthenticator::supports behavior to avoid conflicting with other bundles

---

README.md

This PR removes the quickstart link, as it has been archived as obsolete for some time.

Remove dead link to quickstart documentation

---

composer.json

This PR resolves the following error, raised when `composer compat` is run during CircleCI test tooling.
```sh
dealerdirect/phpcodesniffer-composer-installer contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "dealerdirect/phpcodesniffer-composer-installer" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] 
[Symfony\Component\Console\Exception\RuntimeException]  
Aborted                                                 
```

Fix test suite: resolve "phpcodesniffer-composer-installer" warning during `composer compat`

---

README.md
Tests/Security/Guard/JwtAuthenticatorTest.php
composer.json
src/Resources/config/services.yml
src/Security/Core/JWTInfoNotFoundException.php
src/Security/Guard/AuthenticatorTrait.php
src/Security/Guard/JwtAuthenticator.php
src/Security/Guard/JwtGuardAuthenticator.php

This PR add a new authenticator following[ Symfony > 5.1 guidelines](https://symfony.com/doc/current/security/custom_authenticator.html#security-passports). 
It shouldn't impact the current usage of this library because it requires a specific configuration to use it (see update in readme)
This issue is reported [here](https://github.com/auth0/jwt-auth-bundle/issues/115)
Use Symfony >5.1 and follow the `config/security.yaml` example in readme file.
1. The data given to the user provider is **no more** a jwt object, it's the JWT string. It's due to the new Symfony mechanism that [allows only a string](https://github.com/symfony/security-http/blob/5.3/Authenticator/Passport/Badge/UserBadge.php#L46). I'm pretty sure it's not possible to work with something else than a string. I spend 1 hour …

WIP - Support new Symfony authenticator system

---

src/Auth0Bundle.php
src/Service.php

This PR adds Symfony Cache component support to the SDK. The SDK will invoke the PSR-6-based interface, and connect it directly to the CacheItemPoolInterface property of the Auth0-PHP SDK. This caching feature will be used for JWKS caching to reduce network requests, and caching of Management API tokens generated through the API.
By default, it will use the basic `cache.app` pool, which uses the filesystem adapter. Developers can add new cache pools and define adapters in their `config/package/cache.yaml` file to customize the behavior.

feat: Add Symfony Cache component support

---

src/Auth0Bundle.php
src/Controllers/AuthenticationController.php
src/Security/Authenticator.php
src/Service.php
src/Stores/SessionStore.php

This PR adds Symfony Session storage support to the SDK. At runtime, the SDK will initialize a new StoreInterface bridge-class that allows the underlying Auth0-PHP SDK to store session state using Symfony's session management APIs.
This enables developers to use all the existing Symfony session APIs they're probably already integrated with to engage with authenticated user identities throughout their applications. It also enables developers choice in where session data is stored, including within databases or memory stores like Redis.

feat: Add Symfony Session storage support

---

src/Models/User.php

Please describe both what is changing and why this is important. Include:
I've set custom data in Auth0 via Rules. Currently, it is not possible to retrieve that data from the User class. I've added a getter method to get the custom user data by key. As the content of that data is not known, we have to use mixed as the return type.
An alternative approach would be to make the current private property `data` protected, so I as a developer can extend the User class and get fetch my custom data in my own class.
- https://auth0.com/docs/customize/rules
Create a rule in Auth0, which adds some custom data to e.g. idToken or accessToken with a custom key e.g. `https://mydomain.com/custom_data`.
[x] I have read the [Auth0 general …

Support retrieval of custom data keys from User models

---

README.md

The route `/auth0/logout` isn't defined - the example should be just `/logout`
Tried following the README. Auth0 threw an error when I tried to logout. 
Follow the tutorial on a new machine.
[x] All existing and new tests complete without errors

Correct logout mistake in readme

---

README.md

This PR updates the README to reflect that we do not currently support Symfony 7.
N/A
N/A
[x] All existing and new tests complete without errors

docs: Update README to indicate supported Symfony versions

---

rector.php
src/Security/Authenticator.php
src/Security/Authorizer.php
src/Security/UserProvider.php
src/Service.php
src/Stores/SessionStore.php

5.2.0 inadvertently altered some method signatures due to new code styling tooling rules; this restores those methods to their previous state, to avoid introducing breaking changes.
Resolves #173 
N/A

fix: Restore method signatures

---

src/Controllers/AuthenticationController.php

Please describe both what is changing and why this is important. Include:
- Removing scope keyword from constructor parameter to avoid property re-declaration
- In turn that allows compatibility with both symfony version 6.x and 7.x
- Using given setter to achieve the same desired result
[#178]
Previously Symfony (6.4) app container building (cache:clear) was throwing a fatal error, now it's not.

Do not redeclare controller container property in order to avoid compatibility issues

---

src/Controllers/AuthenticationController.php

Fix syntax typo in the previous code change in `AuthenticationController::__construct()`
https://github.com/auth0/symfony/issues/178
https://github.com/auth0/symfony/pull/179
https://github.com/auth0/symfony/actions/runs/7279226624/job/19835136156
https://github.com/auth0/symfony/actions/runs/7279226624/job/19835137264
[ ] This change has been tested on the latest version of Symfony
[ ] All existing and new tests complete without errors

Fix syntax typo in AuthenticationController::__construct()

---

src/Models/User.php
tests/Unit/Models/UserTest.php

There has been support for Symfony role resolution from both `permissions` and `scope` claims in the JWT tokens for a while now.
However, there was a problem that this bundle expected `scope` claim to be either an array, or a string with the single scope value, while in reality Auth0 authentication API returns tokens with `scope` value being a concatenated string of multiple scope values:
In this bundle such scope produced an unusable role code with spaces in it and all permissions in one string.
This PR fixes this issue, by adding support for concatenated-string scope value while preserving support for previous formats as well.
PhpUnit tests added (both previous formats + the new one; i.e. one test would fail on old codebase)
[x] This change adds test coverage
[ ] This change has been …

feat: Support string concatenation of scopes

---

psalm.xml.dist
src/Controllers/AuthenticationController.php
src/Controllers/BackchannelLogoutController.php

Fix for issue #189
- Removed `$container` parameter from controllers (because it is injected via `setContainer()` by Symfony DI)
- Added exception in psalm config not to report this as a problem
#189
Tested statically and on a Symfony 7.0 project (although controllers are not executed there - verified that container builds without problems and `bin/console list:container` reports no problems)
Tested only statically on Symfony 6.4.
Testing on older Symfony versions would be much appreciated.
[x] I have read the [Auth0 Code of …

Remove $container parameter from controller constructors

---

composer.json

This is simply allowing Symfony 7 in composer.json - could not find any problems or incompatibilities at this point.
- composer.json updated
- all tests (`composer test`) are passing
- tried it out on a minimal Symfony 7 project - no problems found
- though I have only verified the JWT authentication use-case
#182 
Attempted to install this bundle on a small Symfony project and perform JWT authentication. Other use-cases should be verified.
Maybe instead of merging to `main` branch, this should be "quarantined" in a dedicated branch (e.g. `symfony7`) of this main repository - that way other people would be able to install this version via composer by requiring `auth0/symfony: dev-symfony7` and then test on their applications and their use-cases?
[x] This …

Allow symfony-7 in composer.json

---

src/Models/User.php

When converting permissions/scopes to Symfony roles, apply replacement not only for colon (`:`) character, but also for dash (`-`) character, as some resources/permissions consist of multiple words and dash is a recommended separator in such cases.
- Have a permission/scope in Auth0 token that contains a dash (e.g. `read:licence-plates`)
- Convert it to Symfony roles (by getting the roles of the JWT authenticated user/m2m):
- before: it would return `ROLE_READ_LICENCE-PLATES`
- after: it returns `ROLE_READ_LICENCE_PLATES`
[ ] This change has been tested on the latest version of Symfony
[x] I have read the [Auth0 …

Normalize dashes in JWT permissions/scopes
